import Head from "next/head";
import { Poppins } from "next/font/google";
import Header from "@/components/header";
import Hero from "@/components/hero";
import PropertyTypes from "@/components/propertytypes";
import SampleOMS from "@/components/sampleoms";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["700", "600", "400"],
});
export default function Home() {
  return (
    <>
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={poppins.className}>
        <Header />
        <Hero />
        <PropertyTypes />
        <SampleOMS />
      </div>
    </>
  );
}
